name: Our First Workgflow
on: oush

jobs:  
  build:
    name: Fire off my action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions/first-action
        with: 
          AGE: "42"
